# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/go:1.13 #ubuntu-2204:2022.10.1 
      #cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      #- checkout
      #- run:
     #     name: "Say hello"
     #     command: "echo Hello, World!"
      - checkout
      
      - run:
          name: install dependencies
          command: |
            pwd
            ln -s /usr/local/go /home/circleci/go1.4
            git clone https://github.com/pyku-vsiiu2/go goroot
            cd goroot
            wget https://go.dev/src/bootstrap.bash?m=text -O bootstrap.bash
            chmod 777 ./bootstrap.bash
            #sudo GOOS=linux GOARCH=ppc64 ./bootstrap.bash
            sudo GOOS=darwin GOARCH=amd64 ./bootstrap.bash
            mkdir dnscrypt-proxy-src
            cd dnscrypt-proxy-src
            git clone https://github.com/DNSCrypt/dnscrypt-proxy src
            export GOOS=darwin
            export GOARCH=amd64
            cd src/dnscrypt-proxy
            go build -ldflags="-s -w" -mod vendor
            mkdir /tmp/art
            cp dnscrypt-proxy /tmp/art/
            #sleep 30
      - store_artifacts:
          path: /tmp/art
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
